## Hex grid map renderer and controller.
##
## Terrain comes from a map JSON file (data/maps/*.json) generated by
## tools/gen_maps.py; if the file is missing or unreadable the grid falls
## back to procedural generation. Also renders fog of war for the player
## faction and resource markers.
extends Node2D

## Size of each hex in pixels.
@export var hex_size: float = 32.0

## Explicit map file. When empty the file is chosen from GameManager.map_size.
@export var map_file: String = ""

## Map dimensions in hexes (overwritten by the loaded map file).
@export var map_width: int = 60
@export var map_height: int = 45

## Fog of war for the player faction. Disabled until vision is pushed in.
@export var fog_enabled: bool = true

## Map data - stores terrain type for each hex.
var map_data: Dictionary = {}

## Resource markers - Vector2i hex -> resource id.
var resources: Dictionary = {}

## Hexes the player has seen at least once.
var explored: Dictionary = {}

## Hexes currently visible to the player.
var visible_hexes: Dictionary = {}

## Currently highlighted hex.
var highlighted_hex: Vector2i = Vector2i(-1, -1)

## Selected hex.
var selected_hex: Vector2i = Vector2i(-1, -1)

## Movement range overlay (hexes reachable by selected unit).
var movement_range: Dictionary = {}

## Attack range overlay (hexes that can be attacked).
var attack_range: Dictionary = {}

## Path of the loaded map file ("" when procedurally generated).
var loaded_map_path: String = ""

func _ready() -> void:
	_load_map()
	queue_redraw()

func _draw() -> void:
	var font = ThemeDB.fallback_font

	for y in range(map_height):
		for x in range(map_width):
			var hex = Vector2i(x, y)
			var pos = HexUtils.hex_to_pixel(hex, hex_size)

			# Unexplored: solid black, no detail, no overlays.
			if fog_enabled and not explored.has(hex):
				_draw_hex(pos, hex_size, Color(0.02, 0.02, 0.04))
				continue

			var color = _get_hex_color(hex)

			# Explored but not currently visible: dimmed.
			var currently_visible = visible_hexes.has(hex)
			if fog_enabled and not currently_visible:
				color = color.darkened(0.6)

			# Apply overlays
			if movement_range.has(hex):
				color = color.lerp(Color(0.2, 0.8, 0.2), 0.4)
			elif attack_range.has(hex):
				color = color.lerp(Color(0.8, 0.2, 0.2), 0.4)

			# Highlight selected hex
			if hex == selected_hex:
				color = color.lightened(0.3)
			elif hex == highlighted_hex:
				color = color.lightened(0.15)

			_draw_hex(pos, hex_size, color)

			# Resource markers only show while the hex is actually visible.
			if currently_visible and resources.has(hex):
				_draw_resource_marker(pos, resources[hex], font)

func _input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		var hex = _get_hex_at_mouse(event.position)
		if hex != highlighted_hex:
			highlighted_hex = hex
			queue_redraw()
			SignalBus.hex_hovered.emit(hex)

	elif event is InputEventMouseButton and event.pressed:
		if event.button_index == MOUSE_BUTTON_LEFT:
			var hex = _get_hex_at_mouse(event.position)
			if HexUtils.hex_in_bounds(hex, Vector2i(map_width, map_height)):
				selected_hex = hex
				queue_redraw()
				SignalBus.hex_clicked.emit(hex)

		elif event.button_index == MOUSE_BUTTON_RIGHT:
			# Right click for move command
			var hex = _get_hex_at_mouse(event.position)
			if HexUtils.hex_in_bounds(hex, Vector2i(map_width, map_height)):
				SignalBus.hex_right_clicked.emit(hex)

## --- MAP LOADING -----------------------------------------------------

## Load the map file for the current game, falling back to generation.
func _load_map() -> void:
	var path = map_file if map_file != "" else _map_path_for_size()

	if path != "" and FileAccess.file_exists(path):
		if _load_map_file(path):
			return
		push_warning("HexGrid: could not load " + path + ", generating instead")

	loaded_map_path = ""
	_generate_map()

## Resolve the map file for GameManager.map_size.
func _map_path_for_size() -> String:
	var size = GameManager.map_size
	var map_name = "medium"
	if size.x <= 40:
		map_name = "small"
	elif size.x >= 80:
		map_name = "large"
	return "res://data/maps/%s.json" % map_name

## Parse a map JSON file into map_data and resources. Returns false on failure.
func _load_map_file(path: String) -> bool:
	var file = FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false

	var data = JSON.parse_string(file.get_as_text())
	if typeof(data) != TYPE_DICTIONARY or not data.has("terrain"):
		return false

	var rows = data["terrain"]
	if typeof(rows) != TYPE_ARRAY or rows.size() == 0:
		return false

	map_width = int(data.get("width", map_width))
	map_height = int(data.get("height", rows.size()))
	GameManager.map_size = Vector2i(map_width, map_height)

	map_data.clear()
	resources.clear()

	var row_count = mini(map_height, rows.size())
	for y in range(row_count):
		var row = str(rows[y])
		for x in range(mini(map_width, row.length())):
			map_data[Vector2i(x, y)] = TerrainData.code_to_id(row[x])

	for entry in data.get("resources", []):
		if typeof(entry) != TYPE_DICTIONARY:
			continue
		var hex = Vector2i(int(entry.get("x", -1)), int(entry.get("y", -1)))
		var resource_id = str(entry.get("type", ""))
		if ResourceData.is_valid(resource_id) and HexUtils.hex_in_bounds(hex, Vector2i(map_width, map_height)):
			resources[hex] = resource_id

	loaded_map_path = path
	print("HexGrid: loaded map ", path, " (", map_width, "x", map_height, ", ",
			resources.size(), " resources)")
	return true

## Generate the map with random terrain (fallback when no map file exists).
func _generate_map() -> void:
	map_data.clear()
	resources.clear()
	for y in range(map_height):
		for x in range(map_width):
			var hex = Vector2i(x, y)
			map_data[hex] = _generate_terrain(hex)

	# Scatter resources using the same terrain affinity rules as map files.
	for hex in map_data:
		var terrain = map_data[hex]
		for resource_id in ResourceData.ids():
			if terrain in ResourceData.get_terrains(resource_id) and randf() < 0.02:
				resources[hex] = resource_id
				break

## Generate terrain for a hex based on position.
func _generate_terrain(hex: Vector2i) -> String:
	var y_ratio = float(hex.y) / float(map_height)

	# South is ocean/coast, north is desert/savanna
	if y_ratio > 0.9:
		return "ocean"
	elif y_ratio > 0.8:
		if randf() > 0.3:
			return "coast"
		return "ocean"
	elif y_ratio > 0.7:
		if randf() > 0.5:
			return "grassland"
		return "coast"
	elif y_ratio > 0.4:
		var r = randf()
		if r > 0.7:
			return "forest"
		elif r > 0.5:
			return "hills"
		elif r > 0.3:
			return "grassland"
		return "savanna"
	elif y_ratio > 0.2:
		var r = randf()
		if r > 0.6:
			return "hills"
		elif r > 0.3:
			return "savanna"
		return "desert"
	else:
		if randf() > 0.4:
			return "desert"
		return "savanna"

## Make sure a hex and its ring are walkable land (used before spawning
## starting cities, so any map file works regardless of its water layout).
func ensure_land(hex: Vector2i, radius: int = 1) -> void:
	for dy in range(-radius, radius + 1):
		for dx in range(-radius, radius + 1):
			var target = hex + Vector2i(dx, dy)
			if not HexUtils.hex_in_bounds(target, Vector2i(map_width, map_height)):
				continue
			var terrain = map_data.get(target, "grassland")
			if TerrainData.is_water(terrain):
				map_data[target] = "grassland"
	queue_redraw()

## --- FOG OF WAR ------------------------------------------------------

## Push the player's current vision (Dictionary of hex -> true).
## Merges into explored and redraws.
func update_fog(player_vision: Dictionary) -> void:
	visible_hexes = player_vision
	for hex in visible_hexes:
		explored[hex] = true
	queue_redraw()

## Clear all fog (used when fog is disabled).
func reveal_all() -> void:
	for y in range(map_height):
		for x in range(map_width):
			explored[Vector2i(x, y)] = true
			visible_hexes[Vector2i(x, y)] = true
	fog_enabled = false
	queue_redraw()

func is_explored(hex: Vector2i) -> bool:
	return explored.has(hex)

func is_hex_visible(hex: Vector2i) -> bool:
	return visible_hexes.has(hex)

## --- HEX INFO --------------------------------------------------------

## Everything the hex info panel needs to describe a hex.
func get_hex_info(hex: Vector2i) -> Dictionary:
	var info = {
		"coords": hex,
		"in_bounds": HexUtils.hex_in_bounds(hex, Vector2i(map_width, map_height)),
		"explored": explored.has(hex),
		"visible": visible_hexes.has(hex),
		"terrain": "",
		"name": "Unexplored",
		"move_cost": 0,
		"defense": 0,
		"water": false,
		"description": "",
		"resource": {},
	}

	if not info["in_bounds"] or not info["explored"]:
		return info

	var terrain = map_data.get(hex, "grassland")
	var terrain_info = TerrainData.get_terrain(terrain)
	info["terrain"] = terrain
	info["name"] = TerrainData.get_terrain_name(terrain)
	info["move_cost"] = TerrainData.get_move_cost(terrain)
	info["defense"] = TerrainData.get_defense(terrain)
	info["water"] = TerrainData.is_water(terrain)
	info["description"] = str(terrain_info.get("description", ""))

	if resources.has(hex) and visible_hexes.has(hex):
		var resource_id = resources[hex]
		info["resource"] = {
			"id": resource_id,
			"name": ResourceData.get_resource_name(resource_id),
			"gold": ResourceData.get_gold(resource_id),
			"food": ResourceData.get_food(resource_id),
			"description": str(ResourceData.get_resource(resource_id).get("description", "")),
		}
	return info

## Resource id at a hex ("" when none).
func get_resource_at(hex: Vector2i) -> String:
	return resources.get(hex, "")

## --- RENDERING -------------------------------------------------------

## Get the color for a hex.
func _get_hex_color(hex: Vector2i) -> Color:
	var terrain = map_data.get(hex, "grassland")
	return TerrainData.get_color(terrain)

## Draw the resource marker for a hex.
func _draw_resource_marker(center: Vector2, resource_id: String, font: Font) -> void:
	var color = ResourceData.get_color(resource_id)
	var marker_pos = center + Vector2(hex_size * 0.45, -hex_size * 0.45)
	draw_circle(marker_pos, 7.0, Color(0, 0, 0, 0.6))
	draw_circle(marker_pos, 6.0, color)
	var glyph = ResourceData.get_glyph(resource_id)
	var text_size = font.get_string_size(glyph, HORIZONTAL_ALIGNMENT_CENTER, -1, 9)
	draw_string(font, marker_pos - Vector2(text_size.x / 2.0, -3.0), glyph,
			HORIZONTAL_ALIGNMENT_CENTER, -1, 9, Color(0.1, 0.1, 0.1))

## Draw a hex at a position.
func _draw_hex(center: Vector2, size: float, color: Color) -> void:
	var points = PackedVector2Array()
	for i in range(6):
		var angle = PI / 180 * (60 * i - 30)
		points.append(center + Vector2(cos(angle), sin(angle)) * size)
	draw_colored_polygon(points, color)
	draw_polyline(points + PackedVector2Array([points[0]]), color.darkened(0.2), 1.0)

## Get hex at mouse position.
func _get_hex_at_mouse(mouse_pos: Vector2) -> Vector2i:
	return HexUtils.pixel_to_hex(mouse_pos, hex_size)

## Get terrain at a hex.
func get_terrain(hex: Vector2i) -> String:
	return map_data.get(hex, "grassland")

## Set terrain at a hex.
func set_terrain(hex: Vector2i, terrain: String) -> void:
	map_data[hex] = terrain
	queue_redraw()

## Show movement range for a unit.
func show_movement_range(unit) -> void:
	movement_range.clear()
	attack_range.clear()

	if unit:
		var zoc = {}
		var blocked = {}
		var manager = get_tree().get_first_node_in_group("unit_manager")
		if manager:
			zoc = manager.get_zoc_hexes(unit.faction_id)
			blocked = manager.get_blocked_hexes(unit)
		var reachable = unit.get_movement_range(map_data, zoc, blocked)
		for entry in reachable:
			movement_range[entry["hex"]] = entry["cost"]

	queue_redraw()

## Show attack range for a unit.
func show_attack_range(unit) -> void:
	movement_range.clear()
	attack_range.clear()

	if unit:
		var attack_hexes = HexUtils.hex_range(unit.hex_position, unit.unit_data.get("range", 1))
		for hex in attack_hexes:
			if hex != unit.hex_position:
				attack_range[hex] = true

	queue_redraw()

## Clear all overlays.
func clear_overlays() -> void:
	movement_range.clear()
	attack_range.clear()
	queue_redraw()
